<?php

/**
 * @file
 * d8dw Paragraphs module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use \Drupal\file\Entity\File;
use Drupal\file\FileInterface;
use Drupal\image\Entity\ImageStyle;
use Drupal\Core\Render\Element;
use Drupal\paragraphs\Entity\Paragraph;

/**
 * Implements hook_help().
 */
function d8dw_paragraphs_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the paragraphs_types module.
    case 'help.page.d8dw_paragraphs':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is a collection of paragraphs types for Drupal 8.') . '</p>';
      $output .= '<p>' . t('Go to <a href="/admin/structure/d8dw_paragraphs"><code>admin/structure/d8dw_paragraphs</code></a> to see all paragraphs.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function d8dw_paragraphs_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__dw_geosearch' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__dw_teaser' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__dw_tagboard' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__dw_ourbeers' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__dw_traditionandorigin' => [
      'base hook' => 'paragraph',
    ],
  ];
}

function d8dw_paragraphs_uninstall() {
  $files = [
    'core.entity_form_display.paragraph.dw_geosearch.default.yml',
    'core.entity_form_display.paragraph.dw_ourbeers.default.yml',
    'core.entity_form_display.paragraph.dw_tagboard.default.yml',
    'core.entity_form_display.paragraph.dw_teaser.default.yml',
    'core.entity_form_display.paragraph.dw_traditionandorigin.default.yml',

    'core.entity_view_display.paragraph.dw_geosearch.default.yml',
    'core.entity_view_display.paragraph.dw_ourbeers.default.yml',
    'core.entity_view_display.paragraph.dw_tagboard.default.yml',
    'core.entity_view_display.paragraph.dw_teaser.default.yml',
    'core.entity_view_display.paragraph.dw_traditionandorigin.default.yml',

    'field.field.paragraph.dw_geosearch.dw_dealership.yml',
    'field.field.paragraph.dw_ourbeers.dw_ourbeers_aufklappimage.yml',
    'field.field.paragraph.dw_ourbeers.dw_ourbeers_beertext.yml',
    'field.field.paragraph.dw_ourbeers.dw_ourbeers_headline.yml',
    'field.field.paragraph.dw_ourbeers.dw_ourbeers_kachelimage.yml',
    'field.field.paragraph.dw_tagboard.tgb_animation_type.yml',
    'field.field.paragraph.dw_tagboard.tgb_auto_load.yml',
    'field.field.paragraph.dw_tagboard.tgb_feed_type.yml',
    'field.field.paragraph.dw_tagboard.tgb_fixed_height.yml',
    'field.field.paragraph.dw_tagboard.tgb_font_color.yml',
    'field.field.paragraph.dw_tagboard.tgb_gutter.yml',
    'field.field.paragraph.dw_tagboard.tgb_hashtag_color.yml',
    'field.field.paragraph.dw_tagboard.tgb_in_frame_modals.yml',
    'field.field.paragraph.dw_tagboard.tgb_inverted.yml',
    'field.field.paragraph.dw_tagboard.tgb_layout.yml',
    'field.field.paragraph.dw_tagboard.tgb_media_only.yml',
    'field.field.paragraph.dw_tagboard.tgb_mobile_count.yml',
    'field.field.paragraph.dw_tagboard.tgb_post_count.yml',
    'field.field.paragraph.dw_tagboard.tgb_rounded_corners.yml',
    'field.field.paragraph.dw_tagboard.tgb_show_partial_rows.yml',
    'field.field.paragraph.dw_tagboard.tgb_slug.yml',
    'field.field.paragraph.dw_tagboard.tgb_toolbar.yml',
    'field.field.paragraph.dw_teaser.dw_align.yml',
    'field.field.paragraph.dw_teaser.dw_background.yml',
    'field.field.paragraph.dw_teaser.dw_link.yml',
    'field.field.paragraph.dw_teaser.dw_linkable.yml',
    'field.field.paragraph.dw_teaser.dw_teaser_field_desktop.yml',
    'field.field.paragraph.dw_teaser.dw_teaser_field_mobile.yml',
    'field.field.paragraph.dw_teaser.dw_text.yml',
    'field.field.paragraph.dw_teaser.dw_width.yml',
    'field.field.paragraph.dw_traditionandorigin.dw_traditionandorigin_headline.yml',
    'field.field.paragraph.dw_traditionandorigin.dw_traditionandorigin_image.yml',
    'field.field.paragraph.dw_traditionandorigin.dw_traditionandorigin_imageheadline.yml',
    'field.field.paragraph.dw_traditionandorigin.dw_traditionandorigin_imagesubline.yml',
    'field.field.paragraph.dw_traditionandorigin.dw_traditionandorigin_text.yml',

    'field.storage.paragraph.dw_align.yml',
    'field.storage.paragraph.dw_background.yml',
    'field.storage.paragraph.dw_dealership.yml',
    'field.storage.paragraph.dw_link.yml',
    'field.storage.paragraph.dw_linkable.yml',
    'field.storage.paragraph.dw_ourbeers_aufklappimage.yml',
    'field.storage.paragraph.dw_ourbeers_beertext.yml',
    'field.storage.paragraph.dw_ourbeers_headline.yml',
    'field.storage.paragraph.dw_ourbeers_kachelimage.yml',
    'field.storage.paragraph.dw_teaser_field_desktop.yml',
    'field.storage.paragraph.dw_teaser_field_mobile.yml',
    'field.storage.paragraph.dw_text.yml',
    'field.storage.paragraph.dw_traditionandorigin_headline.yml',
    'field.storage.paragraph.dw_traditionandorigin_image.yml',
    'field.storage.paragraph.dw_traditionandorigin_imageheadline.yml',
    'field.storage.paragraph.dw_traditionandorigin_imagesubline.yml',
    'field.storage.paragraph.dw_traditionandorigin_text.yml',
    'field.storage.paragraph.dw_width.yml',
    'field.storage.paragraph.tgb_animation_type.yml',
    'field.storage.paragraph.tgb_auto_load.yml',
    'field.storage.paragraph.tgb_feed_type.yml',
    'field.storage.paragraph.tgb_fixed_height.yml',
    'field.storage.paragraph.tgb_font_color.yml',
    'field.storage.paragraph.tgb_gutter.yml',
    'field.storage.paragraph.tgb_hashtag_color.yml',
    'field.storage.paragraph.tgb_in_frame_modals.yml',
    'field.storage.paragraph.tgb_inverted.yml',
    'field.storage.paragraph.tgb_layout.yml',
    'field.storage.paragraph.tgb_media_only.yml',
    'field.storage.paragraph.tgb_mobile_count.yml',
    'field.storage.paragraph.tgb_post_count.yml',
    'field.storage.paragraph.tgb_rounded_corners.yml',
    'field.storage.paragraph.tgb_show_partial_rows.yml',
    'field.storage.paragraph.tgb_slug.yml',
    'field.storage.paragraph.tgb_toolbar.yml',

    'paragraphs.paragraphs_type.dw_geosearch.yml',
    'paragraphs.paragraphs_type.dw_ourbeers.yml',
    'paragraphs.paragraphs_type.dw_tagboard.yml',
    'paragraphs.paragraphs_type.dw_teaser.yml',
    'paragraphs.paragraphs_type.dw_traditionandorigin.yml',


  ];

  foreach ($files as $file) {
    \Drupal::configFactory()->getEditable($file)->delete();
  }
}