<?php

/**
 * @file
 * d8dw Paragraphs module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use \Drupal\file\Entity\File;
use Drupal\file\FileInterface;
use Drupal\image\Entity\ImageStyle;
use Drupal\Core\Render\Element;
use Drupal\paragraphs\Entity\Paragraph;

/**
 * Implements hook_help().
 */
function d8dw_paragraphs_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the paragraphs_types module.
    case 'help.page.d8dw_paragraphs':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is a collection of paragraphs types for Drupal 8.') . '</p>';
      $output .= '<p>' . t('Go to <a href="/admin/structure/d8dw_paragraphs"><code>admin/structure/d8dw_paragraphs</code></a> to see all paragraphs.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function d8dw_paragraphs_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__dw_geosearch' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__dw_teaser' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__dw_tagboard' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__dw_ourbeers' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__dw_traditionandorigin' => [
      'base hook' => 'paragraph',
    ],
  ];
}

function d8dw_paragraphs_uninstall() {
  $files = [
    'core.entity_form_display.paragraph.dw_geosearch.default',
    'core.entity_form_display.paragraph.dw_ourbeers.default',
    'core.entity_form_display.paragraph.dw_tagboard.default',
    'core.entity_form_display.paragraph.dw_teaser.default',
    'core.entity_form_display.paragraph.dw_traditionandorigin.default',

    'core.entity_view_display.paragraph.dw_geosearch.default',
    'core.entity_view_display.paragraph.dw_ourbeers.default',
    'core.entity_view_display.paragraph.dw_tagboard.default',
    'core.entity_view_display.paragraph.dw_teaser.default',
    'core.entity_view_display.paragraph.dw_traditionandorigin.default',

    'field.field.paragraph.dw_geosearch.dw_dealership',
    'field.field.paragraph.dw_ourbeers.dw_ourbeers_aufklappimage',
    'field.field.paragraph.dw_ourbeers.dw_ourbeers_beertext',
    'field.field.paragraph.dw_ourbeers.dw_ourbeers_headline',
    'field.field.paragraph.dw_ourbeers.dw_ourbeers_kachelimage',
    'field.field.paragraph.dw_tagboard.tgb_animation_type',
    'field.field.paragraph.dw_tagboard.tgb_auto_load',
    'field.field.paragraph.dw_tagboard.tgb_feed_type',
    'field.field.paragraph.dw_tagboard.tgb_fixed_height',
    'field.field.paragraph.dw_tagboard.tgb_font_color',
    'field.field.paragraph.dw_tagboard.tgb_gutter',
    'field.field.paragraph.dw_tagboard.tgb_hashtag_color',
    'field.field.paragraph.dw_tagboard.tgb_in_frame_modals',
    'field.field.paragraph.dw_tagboard.tgb_inverted',
    'field.field.paragraph.dw_tagboard.tgb_layout',
    'field.field.paragraph.dw_tagboard.tgb_media_only',
    'field.field.paragraph.dw_tagboard.tgb_mobile_count',
    'field.field.paragraph.dw_tagboard.tgb_post_count',
    'field.field.paragraph.dw_tagboard.tgb_rounded_corners',
    'field.field.paragraph.dw_tagboard.tgb_show_partial_rows',
    'field.field.paragraph.dw_tagboard.tgb_slug',
    'field.field.paragraph.dw_tagboard.tgb_toolbar',
    'field.field.paragraph.dw_teaser.dw_align',
    'field.field.paragraph.dw_teaser.dw_background',
    'field.field.paragraph.dw_teaser.dw_link',
    'field.field.paragraph.dw_teaser.dw_linkable',
    'field.field.paragraph.dw_teaser.dw_teaser_field_desktop',
    'field.field.paragraph.dw_teaser.dw_teaser_field_mobile',
    'field.field.paragraph.dw_teaser.dw_text',
    'field.field.paragraph.dw_teaser.dw_width',
    'field.field.paragraph.dw_traditionandorigin.dw_traditionandorigin_headline',
    'field.field.paragraph.dw_traditionandorigin.dw_traditionandorigin_image',
    'field.field.paragraph.dw_traditionandorigin.dw_traditionandorigin_imageheadline',
    'field.field.paragraph.dw_traditionandorigin.dw_traditionandorigin_imagesubline',
    'field.field.paragraph.dw_traditionandorigin.dw_traditionandorigin_text',

    'field.storage.paragraph.dw_align',
    'field.storage.paragraph.dw_background',
    'field.storage.paragraph.dw_dealership',
    'field.storage.paragraph.dw_link',
    'field.storage.paragraph.dw_linkable',
    'field.storage.paragraph.dw_ourbeers_aufklappimage',
    'field.storage.paragraph.dw_ourbeers_beertext',
    'field.storage.paragraph.dw_ourbeers_headline',
    'field.storage.paragraph.dw_ourbeers_kachelimage',
    'field.storage.paragraph.dw_teaser_field_desktop',
    'field.storage.paragraph.dw_teaser_field_mobile',
    'field.storage.paragraph.dw_text',
    'field.storage.paragraph.dw_traditionandorigin_headline',
    'field.storage.paragraph.dw_traditionandorigin_image',
    'field.storage.paragraph.dw_traditionandorigin_imageheadline',
    'field.storage.paragraph.dw_traditionandorigin_imagesubline',
    'field.storage.paragraph.dw_traditionandorigin_text',
    'field.storage.paragraph.dw_width',
    'field.storage.paragraph.tgb_animation_type',
    'field.storage.paragraph.tgb_auto_load',
    'field.storage.paragraph.tgb_feed_type',
    'field.storage.paragraph.tgb_fixed_height',
    'field.storage.paragraph.tgb_font_color',
    'field.storage.paragraph.tgb_gutter',
    'field.storage.paragraph.tgb_hashtag_color',
    'field.storage.paragraph.tgb_in_frame_modals',
    'field.storage.paragraph.tgb_inverted',
    'field.storage.paragraph.tgb_layout',
    'field.storage.paragraph.tgb_media_only',
    'field.storage.paragraph.tgb_mobile_count',
    'field.storage.paragraph.tgb_post_count',
    'field.storage.paragraph.tgb_rounded_corners',
    'field.storage.paragraph.tgb_show_partial_rows',
    'field.storage.paragraph.tgb_slug',
    'field.storage.paragraph.tgb_toolbar',

    'paragraphs.paragraphs_type.dw_geosearch',
    'paragraphs.paragraphs_type.dw_ourbeers',
    'paragraphs.paragraphs_type.dw_tagboard',
    'paragraphs.paragraphs_type.dw_teaser',
    'paragraphs.paragraphs_type.dw_traditionandorigin',


  ];

  foreach ($files as $file) {
    \Drupal::configFactory()->getEditable($file)->delete();
  }
}