<?php

/**
 * @file
 * d8dw Paragraphs module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use \Drupal\file\Entity\File;
use Drupal\file\FileInterface;
use Drupal\image\Entity\ImageStyle;
use Drupal\Core\Render\Element;
use Drupal\paragraphs\Entity\Paragraph;

/**
 * Implements hook_help().
 */
function d8dw_paragraphs_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the paragraphs_types module.
    case 'help.page.d8dw_paragraphs':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is a collection of paragraphs types for Drupal 8.') . '</p>';
      $output .= '<p>' . t('Go to <a href="/admin/structure/paragraphs_type"><code>admin/structure/paragraphs_type</code></a> to see all paragraphs.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function d8dw_paragraphs_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__dw_geosearch' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__dw_teaser' => [
      'base hook' => 'paragraph',
    ],
  ];
}

function d8dw_paragraphs_uninstall() {
  $files = [
    'paragraphs.paragraphs_type.dw_teaser',
    'paragraphs.paragraphs_type.dw_geosearch',

    'field.field.paragraph.dw_geosearch.dw_dealership',
    'field.field.paragraph.dw_teaser.dw_align',
    'field.field.paragraph.dw_teaser.dw_background',
    'field.field.paragraph.dw_teaser.dw_link',
    'field.field.paragraph.dw_teaser.dw_teaser_field',
    'field.field.paragraph.dw_teaser.dw_text',
    'field.field.paragraph.dw_teaser.dw_width',

    'field.storage.paragraph.dw_teaser.dw_align',
    'field.storage.paragraph.dw_teaser.dw_background',
    'field.storage.paragraph.dw_teaser.dw_dealership',
    'field.storage.paragraph.dw_teaser.dw_link',
    'field.storage.paragraph.dw_teaser.dw_teaser_field',
    'field.storage.paragraph.dw_teaser.dw_text',
    'field.storage.paragraph.dw_teaser.dw_width',

    'core.entity_form_display.paragraph.dw_geosearch.default',
    'core.entity_form_display.paragraph.dw_teaser.default',

    'core.entity_view_display.paragraph.dw_geosearch.default',
    'core.entity_view_display.paragraph.dw_teaser.default',
  ];

  foreach ($files as $file) {
    \Drupal::configFactory()->getEditable($file)->delete();
  }
}